import React, { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence, useScroll, useSpring } from "framer-motion";
import {
  ArrowRight,
  Sparkles,
  Search,
  Orbit,
  Menu,
  X,
  Home,
  LayoutGrid,
  BookOpen,
  Info,
  ShoppingBag,
  CheckCircle2,
  Award,
  Layers3,
  Briefcase,
  ShieldCheck,
  Leaf,
  Droplets,
  Sun,
  ChevronRight,
  ExternalLink,
  Mail,
  Microscope,
  BadgeDollarSign,
  Clock3,
  Filter,
  Wand2,
  SlidersHorizontal,
  Thermometer,
  MapPin,
  Package,
  Target,
  Settings2,
  Route,
  LineChart,
  Download,
} from "lucide-react";
import { Button, Card, CardContent } from "./ui";
